const books = [
  {
    status: "active",
    slug: "to-kill-a-mockingbird",
    title: "To Kill a Mockingbird",
    year: 1960,
    author: "Harper Lee",
    imgUrl: "https://example.com/tokillamockingbird.jpg",
    imageList: [
      "https://example.com/tokillamockingbird1.jpg",
      "https://example.com/tokillamockingbird2.jpg",
    ],
    isbn: 9780061120081,
    genre: "Fiction",
    available: true,
    averageRating: 4.8,
    description:
      "A novel about the serious issues of rape and racial inequality.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "the-great-gatsby",
    title: "The Great Gatsby",
    year: 1925,
    author: "F. Scott Fitzgerald",
    imgUrl: "https://example.com/thegreatgatsby.jpg",
    imageList: [],
    isbn: 9780743273565,
    genre: "Classic",
    available: false,
    averageRating: 4.5,
    description:
      "A story of the wealthy Jay Gatsby and his love for Daisy Buchanan.",
    expectedAvailable: "2025-06-01T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "1984",
    title: "1984",
    year: 1949,
    author: "George Orwell",
    imgUrl: "https://example.com/1984.jpg",
    imageList: [],
    isbn: 9780451524935,
    genre: "Dystopian",
    available: true,
    averageRating: 4.6,
    description:
      "A novel about a totalitarian regime and constant surveillance.",
    expectedAvailable: null,
  },
  {
    status: "active",
    slug: "harry-potter-and-the-sorcerers-stone",
    title: "Harry Potter and the Sorcerer's Stone",
    year: 1997,
    author: "J.K. Rowling",
    imgUrl: "https://example.com/harrypotter1.jpg",
    imageList: [
      "https://example.com/harrypotter1-1.jpg",
      "https://example.com/harrypotter1-2.jpg",
    ],
    isbn: 9780590353427,
    genre: "Fantasy",
    available: true,
    averageRating: 4.9,
    description:
      "The first book in the Harry Potter series, introducing the magical world of Hogwarts.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "the-hobbit",
    title: "The Hobbit",
    year: 1937,
    author: "J.R.R. Tolkien",
    imgUrl: "https://example.com/thehobbit.jpg",
    imageList: [],
    isbn: 9780345339683,
    genre: "Fantasy",
    available: false,
    averageRating: 4.7,
    description:
      "A fantasy novel that sets the stage for The Lord of the Rings.",
    expectedAvailable: "2025-07-15T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "pride-and-prejudice",
    title: "Pride and Prejudice",
    year: 1813,
    author: "Jane Austen",
    imgUrl: "https://example.com/prideandprejudice.jpg",
    imageList: [],
    isbn: 9781503290563,
    genre: "Romance",
    available: true,
    averageRating: 4.5,
    description: "A classic novel about love and societal expectations.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "the-catcher-in-the-rye",
    title: "The Catcher in the Rye",
    year: 1951,
    author: "J.D. Salinger",
    imgUrl: "https://example.com/catcherintherye.jpg",
    imageList: [],
    isbn: 9780316769488,
    genre: "Fiction",
    available: false,
    averageRating: 4.3,
    description: "A novel about teenage rebellion and self-discovery.",
    expectedAvailable: "2025-05-20T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "moby-dick",
    title: "Moby-Dick",
    year: 1851,
    author: "Herman Melville",
    imgUrl: "https://example.com/mobydick.jpg",
    imageList: [],
    isbn: 9781503280786,
    genre: "Adventure",
    available: true,
    averageRating: 4.1,
    description: "A story of obsession and revenge on the high seas.",
    expectedAvailable: null,
  },
  {
    status: "active",
    slug: "war-and-peace",
    title: "War and Peace",
    year: 1869,
    author: "Leo Tolstoy",
    imgUrl: "https://example.com/warandpeace.jpg",
    imageList: [],
    isbn: 9781400079988,
    genre: "Historical Fiction",
    available: true,
    averageRating: 4.6,
    description: "A vast epic about war, politics, and human nature.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "crime-and-punishment",
    title: "Crime and Punishment",
    year: 1866,
    author: "Fyodor Dostoevsky",
    imgUrl: "https://example.com/crimeandpunishment.jpg",
    imageList: [],
    isbn: 9780679734505,
    genre: "Psychological Fiction",
    available: false,
    averageRating: 4.7,
    description: "A deep psychological exploration of guilt and redemption.",
    expectedAvailable: "2025-09-10T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "brave-new-world",
    title: "Brave New World",
    year: 1932,
    author: "Aldous Huxley",
    imgUrl: "https://example.com/bravenewworld.jpg",
    imageList: [],
    isbn: 9780060850524,
    genre: "Dystopian",
    available: true,
    averageRating: 4.3,
    description:
      "A futuristic dystopian novel about technological advancements and social control.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "the-lord-of-the-rings",
    title: "The Lord of the Rings",
    year: 1954,
    author: "J.R.R. Tolkien",
    imgUrl: "https://example.com/lordoftherings.jpg",
    imageList: [],
    isbn: 9780618640157,
    genre: "Fantasy",
    available: false,
    averageRating: 4.9,
    description:
      "An epic high-fantasy novel about the quest to destroy the One Ring.",
    expectedAvailable: "2025-10-01T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "frankenstein",
    title: "Frankenstein",
    year: 1818,
    author: "Mary Shelley",
    imgUrl: "https://example.com/frankenstein.jpg",
    imageList: [],
    isbn: 9780486282114,
    genre: "Horror",
    available: true,
    averageRating: 4.2,
    description:
      "A gothic novel exploring the dangers of unchecked scientific ambition.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "anna-karenina",
    title: "Anna Karenina",
    year: 1877,
    author: "Leo Tolstoy",
    imgUrl: "https://example.com/annakarenina.jpg",
    imageList: [],
    isbn: 9780143035008,
    genre: "Classic",
    available: false,
    averageRating: 4.6,
    description: "A tragic love story set in imperial Russia.",
    expectedAvailable: "2025-11-15T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "the-picture-of-dorian-gray",
    title: "The Picture of Dorian Gray",
    year: 1890,
    author: "Oscar Wilde",
    imgUrl: "https://example.com/doriangray.jpg",
    imageList: [],
    isbn: 9780141442464,
    genre: "Philosophical Fiction",
    available: true,
    averageRating: 4.5,
    description:
      "A novel about vanity, morality, and the pursuit of eternal youth.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "the-count-of-monte-cristo",
    title: "The Count of Monte Cristo",
    year: 1844,
    author: "Alexandre Dumas",
    imgUrl: "https://example.com/montecristo.jpg",
    imageList: [],
    isbn: 9780140449266,
    genre: "Adventure",
    available: false,
    averageRating: 4.8,
    description: "A thrilling tale of betrayal, revenge, and justice.",
    expectedAvailable: "2025-12-05T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "one-hundred-years-of-solitude",
    title: "One Hundred Years of Solitude",
    year: 1967,
    author: "Gabriel García Márquez",
    imgUrl: "https://example.com/100yearsofsolitude.jpg",
    imageList: [],
    isbn: 9780060883287,
    genre: "Magical Realism",
    available: true,
    averageRating: 4.6,
    description:
      "A multi-generational story of the Buendía family in the fictional town of Macondo.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "wuthering-heights",
    title: "Wuthering Heights",
    year: 1847,
    author: "Emily Brontë",
    imgUrl: "https://example.com/wutheringheights.jpg",
    imageList: [],
    isbn: 9780141439556,
    genre: "Gothic Fiction",
    available: false,
    averageRating: 4.4,
    description: "A haunting tale of love and revenge on the Yorkshire moors.",
    expectedAvailable: "2025-08-22T00:00:00.000Z",
  },
  {
    status: "active",
    slug: "the-alchemist",
    title: "The Alchemist",
    year: 1988,
    author: "Paulo Coelho",
    imgUrl: "https://example.com/thealchemist.jpg",
    imageList: [],
    isbn: 9780061122415,
    genre: "Fiction",
    available: true,
    averageRating: 4.7,
    description: "A philosophical novel about following one's dreams.",
    expectedAvailable: null,
  },
  {
    status: "inactive",
    slug: "don-quixote",
    title: "Don Quixote",
    year: 1605,
    author: "Miguel de Cervantes",
    imgUrl: "https://example.com/donquixote.jpg",
    imageList: [],
    isbn: 9780060934347,
    genre: "Satire",
    available: false,
    averageRating: 4.3,
    description: "A classic novel about a delusional knight's adventures.",
    expectedAvailable: "2025-09-30T00:00:00.000Z",
  },
];
export default books;
